In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.4


In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [6]:
world = tf.constant('World')

In [7]:
world

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [8]:
result = hello + world

In [9]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [10]:
with tf.Session() as sess:
    res = sess.run(result)

In [11]:
res

b'HelloWorld'

In [13]:
a = tf.constant(1)
b = tf.constant(2)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
type(b)

tensorflow.python.framework.ops.Tensor

In [16]:
x = a + b

In [17]:
type(x)

tensorflow.python.framework.ops.Tensor

In [18]:
sess = tf.Session()

In [19]:
x_res = sess.run(x)

In [20]:
x_res

3

In [21]:
const = tf.constant(10)

In [22]:
fill_mat = tf.fill((4,4),10)

In [23]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [24]:
myzeros = tf.zeros((4,4))

In [25]:
myones = tf.ones((4,4))

In [26]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [27]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [28]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [29]:
my_ops

[<tf.Tensor 'Const_6:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [30]:
# sess = tf.Session()

In [31]:
sess = tf.InteractiveSession()

In [33]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [34]:
sess.run([myzeros, myones])

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)]

In [35]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [36]:
a 

<tf.Tensor 'Const_7:0' shape=(2, 2) dtype=int32>

In [37]:
a.b = tf.constant([[10],[100]])()

TensorShape([Dimension(2), Dimension(2)])

In [38]:
b = tf.constant([[10],[100]])

In [39]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [40]:
a.eval()

array([[1, 2],
       [3, 4]], dtype=int32)

# Tensorflow Graphs

In [1]:
import tensorflow as tf

In [2]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [3]:
n3 = n1 + n2

In [4]:
with tf.Session() as sess:
    result = sess.run(n3)

In [5]:
result

3

In [6]:
tf.get_default_graph()

In [7]:
g = tf.Graph()

In [8]:
g

In [9]:
graph_one = tf.get_default_graph()
graph_two = g

In [10]:
graph_one is tf.get_default_graph()

True

In [11]:
graph_two is tf.get_default_graph()

False

In [13]:
with tf.Session() as sess:
    result = sess.run(n3)
print(result)

3


In [15]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())
    with tf.Session() as sess:
        result = sess.run(n3)
    print(result)

True


RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

# Variables y Placeholders

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

### Variables

In [3]:
my_tensor = tf.random_uniform((4,4),0,1)

In [4]:
my_var = tf.Variable(initial_value=my_tensor)

In [5]:
my_var

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>

In [6]:
init = tf.global_variables_initializer()

In [7]:
init

<tf.Operation 'init' type=NoOp>

In [9]:
sess.run(init)

In [10]:
sess.run(my_var)

array([[0.85093725, 0.15288591, 0.81329024, 0.4923929 ],
       [0.50847566, 0.7928699 , 0.807667  , 0.97231376],
       [0.8090204 , 0.0761615 , 0.16199839, 0.90996087],
       [0.80473876, 0.20395696, 0.8495282 , 0.41205812]], dtype=float32)